insert into employees (name,department_id) values ('Tom', 1);
insert into employees (name,department_id) values ('Sam',2 );
insert into employees (name,department_id) values ('Kate',3 );
insert into employees (name,department_id) values ('Rod',7 );
insert into employees (name,department_id) values ('Ham',7 );
insert into employees (name,department_id) values ('Line', 4);
insert into employees (name,department_id) values ('Pol', 5);
insert into employees (name,department_id) values ('Sara', 3);
insert into employees (name,department_id) values ('Flare',2 );
insert into employees (name) values ('Graig');
insert into employees (name) values ('Nate');
insert into employees (name) values ('Jone');